<a href="https://colab.research.google.com/github/minalduggal/Titanic-Project/blob/main/Titanic.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings('ignore')

In [3]:
df=sns.load_dataset("titanic")

In [4]:
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True


In [5]:
df.columns

Index(['survived', 'pclass', 'sex', 'age', 'sibsp', 'parch', 'fare',
       'embarked', 'class', 'who', 'adult_male', 'deck', 'embark_town',
       'alive', 'alone'],
      dtype='object')

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype   
---  ------       --------------  -----   
 0   survived     891 non-null    int64   
 1   pclass       891 non-null    int64   
 2   sex          891 non-null    object  
 3   age          714 non-null    float64 
 4   sibsp        891 non-null    int64   
 5   parch        891 non-null    int64   
 6   fare         891 non-null    float64 
 7   embarked     889 non-null    object  
 8   class        891 non-null    category
 9   who          891 non-null    object  
 10  adult_male   891 non-null    bool    
 11  deck         203 non-null    category
 12  embark_town  889 non-null    object  
 13  alive        891 non-null    object  
 14  alone        891 non-null    bool    
dtypes: bool(2), category(2), float64(2), int64(4), object(5)
memory usage: 80.7+ KB


In [7]:
df.drop(['alive', 'class', 'who', 'adult_male', 'deck', 'embark_town'],axis=1,inplace=True)

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 9 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   survived  891 non-null    int64  
 1   pclass    891 non-null    int64  
 2   sex       891 non-null    object 
 3   age       714 non-null    float64
 4   sibsp     891 non-null    int64  
 5   parch     891 non-null    int64  
 6   fare      891 non-null    float64
 7   embarked  889 non-null    object 
 8   alone     891 non-null    bool   
dtypes: bool(1), float64(2), int64(4), object(2)
memory usage: 56.7+ KB


In [9]:
df["age"].fillna(df["age"].mean(),inplace=True)

In [10]:
df.dropna(subset=["embarked"],inplace=True)

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 889 entries, 0 to 890
Data columns (total 9 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   survived  889 non-null    int64  
 1   pclass    889 non-null    int64  
 2   sex       889 non-null    object 
 3   age       889 non-null    float64
 4   sibsp     889 non-null    int64  
 5   parch     889 non-null    int64  
 6   fare      889 non-null    float64
 7   embarked  889 non-null    object 
 8   alone     889 non-null    bool   
dtypes: bool(1), float64(2), int64(4), object(2)
memory usage: 63.4+ KB


In [12]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
df["sex"]=le.fit_transform(df["sex"])
df["embarked"]=le.fit_transform(df["embarked"])
df=df.astype(int)

In [13]:
X=df.drop("survived",axis=1)
y=df["survived"]

In [14]:
from sklearn.model_selection import train_test_split

X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)



# ***LOGISTIC REGRESSION***

In [15]:
from sklearn.linear_model import LogisticRegression #dont have to do feature scaling
model_lr=LogisticRegression()
model_lr.fit(X_train,y_train)

LogisticRegression()

In [16]:
y_pred=model_lr.predict(X_test)

In [17]:
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report

In [18]:
accuracy_score(y_test,y_pred)

0.8033707865168539

In [19]:
confusion_matrix(y_test,y_pred)

array([[90, 19],
       [16, 53]])

In [20]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.85      0.83      0.84       109
           1       0.74      0.77      0.75        69

    accuracy                           0.80       178
   macro avg       0.79      0.80      0.79       178
weighted avg       0.81      0.80      0.80       178



# ***KNN***

In [21]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()

In [22]:
X_train_scaled=scaler.fit_transform(X_train)
X_test_scaled=scaler.fit_transform(X_test)

In [28]:
from sklearn import neighbors #use standard scaling as we are using distance
from sklearn.neighbors import KNeighborsClassifier
model_knn= KNeighborsClassifier(n_neighbors=5)

In [33]:
model_knn.fit(X_train_scaled,y_train)

KNeighborsClassifier()

In [37]:
y_pred_knn=model_knn.predict(X_test_scaled)

In [40]:
accuracy_score(y_test,y_pred_knn)

0.7752808988764045

In [38]:
confusion_matrix(y_test,y_pred_knn)

array([[89, 20],
       [20, 49]])

In [39]:
print(classification_report(y_test,y_pred_knn))

              precision    recall  f1-score   support

           0       0.82      0.82      0.82       109
           1       0.71      0.71      0.71        69

    accuracy                           0.78       178
   macro avg       0.76      0.76      0.76       178
weighted avg       0.78      0.78      0.78       178



# ***NAIVE BAYES***

In [41]:
#doing naive bayes with and without standard scaling

In [43]:
from sklearn.naive_bayes import GaussianNB

In [45]:
model_nb=GaussianNB()
model_nb.fit(X_train,y_train)

GaussianNB()

In [49]:
y_pred_nb=model_nb.predict(X_test)

In [54]:
accuracy_score(y_test,y_pred_nb)

0.7752808988764045

In [55]:
confusion_matrix(y_test,y_pred_nb)

array([[84, 25],
       [15, 54]])

In [56]:
print(classification_report(y_test,y_pred_nb))

              precision    recall  f1-score   support

           0       0.85      0.77      0.81       109
           1       0.68      0.78      0.73        69

    accuracy                           0.78       178
   macro avg       0.77      0.78      0.77       178
weighted avg       0.78      0.78      0.78       178



# ***DECISION TREE***

In [63]:
from sklearn.tree import DecisionTreeClassifier #do feature scaling here as well
model_dt= DecisionTreeClassifier(random_state=42)

In [66]:
y_pred_dt=model_dt.predict(X_test_scaled)

In [67]:
accuracy_score(y_test,y_pred_dt)

0.7696629213483146

In [68]:
confusion_matrix(y_test,y_pred_dt)

array([[88, 21],
       [20, 49]])

In [69]:
print(classification_report(y_test,y_pred_dt))

              precision    recall  f1-score   support

           0       0.81      0.81      0.81       109
           1       0.70      0.71      0.71        69

    accuracy                           0.77       178
   macro avg       0.76      0.76      0.76       178
weighted avg       0.77      0.77      0.77       178



# ***SUPPORT VECTOR MACHINE***

In [72]:
from sklearn.svm import SVC # do feature scaling here as well
model_svm=SVC(kernel="rbf")

In [73]:
model_svm.fit(X_train_scaled,y_train)

SVC()

In [76]:
y_pred_svm=model_svm.predict(X_test_scaled)

In [77]:
accuracy_score(y_test,y_pred_svm)

0.8258426966292135

In [78]:
confusion_matrix(y_test,y_pred_svm)

array([[96, 13],
       [18, 51]])

In [79]:
print(classification_report(y_test,y_pred_svm))

              precision    recall  f1-score   support

           0       0.84      0.88      0.86       109
           1       0.80      0.74      0.77        69

    accuracy                           0.83       178
   macro avg       0.82      0.81      0.81       178
weighted avg       0.82      0.83      0.82       178



accuracy_score(y_test,y_pred_knn)

confusion_matrix(y_test,y_pred_knn)

print(classification_report(y_test,y_pred_knn))